### ISSUE TITLE
可支持动态写入源文件吗？

### ISSUE THREAD

**Issue by lkeme** [php-mylib/collection#3]
```
set()
```

测试虽然可以改变数组，但是任何更改都不会反应到源文件，也没有见到相关的保存方法

```
set() -> save() or toFile()...
```

**Comment by inhere** [comment]
只是个读配置 合并配置的库。没有支持导出到文件的，有需要可以扩展一下

**Comment by lkeme** [comment]
thx，有这种需要，生态里没有特别全面的config库，有比较完全的读写解析功能的config库也是单一的解析器。

**Comment by inhere** [comment]
其实合并后导出数据到文件很简单，只是这样导出的没有注释了，只能做配置备份

**Comment by inhere** [comment]
v1.1.3 新增了 `exportTo()` 方法导出配置数据到文件

```php
$config->exportTo('/path/to/file.json');
```
